app = "financiallens-beta"
   primary_region = "ams"
   
   [build]
   
   [env]
     PORT = "8501"
     PYTHONUNBUFFERED = "1"
   
   [http_service]
     internal_port = 8501
     force_https = true
     auto_stop_machines = true
     auto_start_machines = true
     min_machines_running = 0
   
   [[vm]]
     memory = '2gb'
     cpu_kind = 'shared'
     cpus = 2
