# ====================================================================================
# ENRICHMENT CONFIGURATION - Financial Statement Parser System
#
# This file contains the complete configuration for Nota Integrativa enrichment
# processing. It defines the three-pass matching strategy used to enrich
# abbreviated format financial statements with detailed breakdowns from
# supplementary tables in the Nota Integrativa section.
#
# The enrichment process is critical for abbreviated format documents where the
# main schema contains summary information but detailed breakdowns are provided
# in supplementary tables that must be identified, extracted, and integrated.
#
# ====================================================================================

# ENRICHMENT RULES
# Defines which sections can be enriched and how to locate relevant tables
enrichment_rules:
  # RECEIVABLES ENRICHMENT
  # Configuration for enriching "II - Crediti" section with detailed breakdown
  'II - Crediti':
    # Title keywords used to locate relevant tables in Nota Integrativa
    titles:
      - 'crediti iscritti nellattivo circolante'
      - 'variazioni e scadenza dei crediti iscritti nellattivo circolante'
      - 'dettaglio dei crediti'
      - 'composizione dei crediti'
      - 'analisi dei crediti'
      - "Crediti iscritti nell'attivo circolante"
    
    # Children patterns define the financial items that can be matched in tables
    children:
      'Crediti verso clienti':
        patterns: 
          - 'crediti verso clienti iscritti'
      
      'Crediti verso imprese controllate (Attivo Circolante)':
        patterns: 
          - 'crediti verso imprese controllate iscritti'
      
      'Crediti verso imprese collegate (Attivo Circolante)':
        patterns: 
          - 'crediti verso imprese collegate iscritti'
      
      'Crediti verso controllanti (Attivo Circolante)':
        patterns: 
          - 'crediti verso controllanti iscritti'
      
      'Crediti verso altri (Attivo Circolante)':
        patterns: 
          - 'crediti verso altri iscritti'
      
      'Crediti verso imprese sottoposte al controllo delle controllanti (Attivo Circolante)':
        patterns: 
          - 'crediti verso imprese sottoposte al controllo iscritti'
      
      'Crediti tributari':
        patterns: 
          - 'crediti tributari iscritti'
      
      'Crediti per imposte anticipate':
        patterns: 
          - 'crediti per imposte anticipate iscritti'

  # PAYABLES ENRICHMENT
  # Configuration for enriching "D) Debiti" section with detailed breakdown
  'D) Debiti':
    # Title keywords used to locate relevant tables in Nota Integrativa
    titles:
      - 'variazioni e scadenza dei debiti'
      - 'dettaglio dei debiti'
      - 'composizione dei debiti'
      - 'analisi dei debiti'
      - 'ripartizione dei debiti'
      - 'debiti per scadenza'
    
    # Children patterns define the financial items that can be matched in tables
    children:
      'Obbligazioni':
        patterns: 
          - 'obbligazioni'
      
      'Obbligazioni convertibili':
        patterns: 
          - 'obbligazioni convertibili'
          - 'convertibili'
      
      'Debiti verso soci per finanziamenti':
        patterns: 
          - 'debiti verso soci per finanziamenti'
          - 'debiti verso soci'
          - 'verso soci per finanziamenti'
          - 'soci per finanziamenti'
      
      'Debiti verso banche':
        patterns: 
          - 'debiti verso banche'
          - 'verso banche'
          - 'banche'
      
      'Debiti verso altri finanziatori':
        patterns: 
          - 'debiti verso altri finanziatori'
          - 'verso altri finanziatori'
          - 'altri finanziatori'
      
      'Acconti':
        patterns: 
          - 'acconti'
      
      'Debiti verso fornitori':
        patterns: 
          - 'debiti verso fornitori'
          - 'verso fornitori'
          - 'fornitori'
      
      'Debiti rappresentati da titoli di credito':
        patterns: 
          - 'debiti rappresentati da titoli di credito'
          - 'rappresentati da titoli di credito'
          - 'titoli di credito'
      
      'Debiti verso imprese controllate':
        patterns: 
          - 'debiti verso imprese controllate'
          - 'verso imprese controllate'
          - 'imprese controllate'
      
      'Debiti verso imprese collegate':
        patterns: 
          - 'debiti verso imprese collegate'
          - 'verso imprese collegate'
          - 'imprese collegate'
      
      'Debiti verso controllanti':
        patterns: 
          - 'debiti verso controllanti'
          - 'verso controllanti'
          - 'controllanti'
      
      'Debiti verso imprese sottoposte al controllo delle controllanti':
        patterns: 
          - 'debiti verso imprese sottoposte al controllo'
          - 'verso imprese sottoposte al controllo'
          - 'imprese sottoposte al controllo'
          - 'sottoposte al controllo'
      
      'Debiti tributari':
        patterns: 
          - 'debiti tributari'
          - 'tributari'
      
      'Debiti verso istituti di previdenza e di sicurezza sociale':
        patterns: 
          - 'debiti verso istituti di previdenza'
          - 'verso istituti di previdenza'
          - 'istituti di previdenza'
          - 'previdenza e sicurezza sociale'
      
      'Altri debiti':
        patterns: 
          - 'altri debiti'

# NOTA INTEGRATIVA COLUMN MAPPING
# Defines the standard column positions in Nota Integrativa tables
# This centralizes what was previously hardcoded in the EnrichmentEngine
nota_integrativa_columns:
  # Standard column mapping for most NI tables
  description: 0        # Column containing item descriptions
  total: 3             # Column containing total values
  short_term: 4        # Column containing amounts due within one year
  long_term: 5         # Column containing amounts due beyond one year

# ENRICHMENT PROCESSING SETTINGS
# Configuration parameters for the enrichment processing logic
processing_settings:
  # Three-pass matching strategy thresholds
  matching_thresholds:
    # Pass 0: Exact pattern matching (highest priority)
    exact_pattern_enabled: true
    
    # Pass 1: High confidence fuzzy matching
    high_confidence_threshold: 95     # Minimum score for high confidence matches
    high_confidence_scorer: "ratio"   # fuzzywuzzy scorer for high confidence pass
    
    # Pass 2: Flexible fuzzy matching
    flexible_threshold: 85            # Minimum score for flexible matches
    flexible_scorer: "WRatio"         # fuzzywuzzy scorer for flexible pass
  
  # Table detection and processing
  table_processing:
    # Maximum pages to search for spanning tables
    max_search_pages: 20
    
    # Header similarity threshold for table continuation
    header_similarity_threshold: 80
  
  # Data validation and integration
  validation:
    # Tolerance for validating NI totals against main schema
    tolerance_percentage: 0.01        # 1% tolerance
    tolerance_minimum: 2.0            # Minimum 2 euro tolerance
    
    # Whether to proceed with integration on validation failure
    strict_validation: true           # Fail integration if validation fails