# ====================================================================================
# MAIN CONFIGURATION - Financial Statement Parser System
# 
# This file contains core processing parameters, system settings, and operational
# thresholds for the financial statement parser.
#
# ====================================================================================

# Core Parser Processing Settings
# These parameters control the fundamental behavior of text matching and processing
parser_settings:
  # Fuzzy matching thresholds for text recognition
  fuzzy_score_threshold: 90                    # Minimum score for accepting fuzzy matches
  ignore_fuzzy_score_threshold: 90             # Threshold for ignore pattern matching
  enrichment_score_threshold: 85               # Standard threshold for enrichment matching
  enrichment_high_confidence_threshold: 95     # High confidence threshold for enrichment first pass

# Advanced Processing Thresholds
# Fine-tuned parameters for specialized processing scenarios
processing_thresholds:
  # Nota Integrativa processing limits
  ni_search_page_limit: 20                     # Maximum pages to search for NI tables
  
  # Retry mechanism settings
  max_retry_attempts: 3                        # Maximum parsing attempts for non-deterministic behavior
  
  # Header similarity for table continuation detection
  table_continuation_threshold: 80             # Similarity threshold for merging spanning tables

# Mathematical Validation Settings
# Parameters controlling the tolerance and precision of financial validations
validation_settings:
  # Tolerance calculation parameters
  tolerance_percentage: 0.01                   # 1% tolerance for relative differences
  tolerance_minimum: 2.0                       # Minimum absolute tolerance in euros
  immediate_success_threshold: 2.0             # Threshold for immediate success classification

# Output File Settings
# Configuration for result file naming and organization
output_settings:
  # File prefixes based on validation status
  prefixes:
    success: ""                                # No prefix for successful parsing
    success_with_tolerance: "SuccessWithTol_"  # Prefix for tolerance-passed results
    failed: "Failed_"                          # Prefix for failed validation results

# PDF Extraction Configuration
# Settings controlling PDF document processing and table extraction
pdf_extraction:
  # Table extraction strategy
  table_settings:
    vertical_strategy: "lines"                 # Strategy for detecting table columns
    horizontal_strategy: "text"                # Strategy for detecting table rows
    min_words_vertical: 2                      # Minimum words for vertical line detection
  
  # Document section detection patterns
  section_patterns:
    stato_patrimoniale: "\\b(stato\\s+patrimoniale)\\b"
    conto_economico: "\\b(conto\\s+economico)\\b"
  
  # Abbreviated format detection patterns (mark BS as abbreviated if at least two of the following sentences are present.)
  abbreviated_format_indicators:
    - "forma abbreviata"
    - "2435-bis"

streamlit_settings:
  max_files: 5
  brsf_scale_default: "/1000"

# System Metadata
# Information about the configuration and system version
metadata:
  config_version: "1.0"                        # Configuration file format version
  system_version: "Public Beta"                # Parser system version
  created_date: "2025"                         # Configuration creation date
  description: "none"
  
  # Compatibility information
  min_python_version: "3.8"                   # Minimum required Python version
  required_dependencies:
    - "pdfplumber"
    - "fuzzywuzzy"
    - "openpyxl"
    - "yaml"